openapi: 3.0.0
info:
  title: OpenWeather
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1:8080'
components:
  securitySchemes:
    APPID:
      name: APPID
      type: apiKey
      in: query
  schemas:
    Response200Schema:
      type: object
      properties:
        coord:
          type: object
          properties:
            lon:
              type: number
            lat:
              type: number
          required:
            - lon
            - lat
          additionalProperties: false
        weather:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              main:
                type: string
              description:
                type: string
              icon:
                type: string
        base:
          type: string
        main:
          type: object
          properties:
            temp:
              type: number
            feels_like:
              type: number
            temp_min:
              type: number
            temp_max:
              type: number
            pressure:
              type: integer
            humidity:
              type: integer
          required:
            - temp
            - feels_like
            - temp_min
            - temp_max
            - pressure
            - humidity
          additionalProperties: false
        visibility:
          type: integer
        wind:
          type: object
          properties:
            speed:
              type: number
            deg:
              type: integer
          required:
            - speed
            - deg
          additionalProperties: false
        clouds:
          type: object
          properties:
            all:
              type: integer
          required:
            - all
          additionalProperties: false
        dt:
          type: integer
        sys:
          type: object
          properties:
            type:
              type: integer
            id:
              type: integer
            country:
              type: string
            sunrise:
              type: integer
            sunset:
              type: integer
          required:
            - type
            - id
            - country
            - sunrise
            - sunset
          additionalProperties: false
        timezone:
          type: integer
        id:
          type: integer
        name:
          type: string
        cod:
          type: integer
      additionalProperties: false
      required:
        - coord
        - weather
        - base
        - main
        - visibility
        - wind
        - clouds
        - dt
        - sys
        - timezone
        - id
        - name
        - cod

    AuthorizationError:
      type: object
      properties:
        cod:
          type: integer
        message:
          type: string
      additionalProperties: false
      required:
        - cod
        - message

paths:
  /data/2.5/weather:
    get:
      tags:
        - default
      summary: Get weather by city name
      security:
        - APPID: []
      parameters:
        - name: q
          in: query
          schema:
            type: string
            maxLength: 150
            minLength: 2
            pattern: '^[a-zA-Z\s]*$'
          example: london
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response200Schema"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizationError'  
      
      operationId: GetWeatherByName
security:
  - APPID: []
